config: .markdownlint.jsonc
globs:
  - "README.md"
  - "CONTRIBUTING.md"
  - "AGENTLAB_DEV_SPECIFICATION.md"
  - "PROXMOX_SPECS.md"
  - "docs/**/*.md"
ignores:
  - ".markdownlint-cli2.yaml"
  - "bin/**"
  - "dist/**"
  - "coverage.html"
  - "coverage.out"
